name: "XMRig miner"
description: "Mine Monero in Home Assistant"
version: "0.1.2"
slug: "xmrig-miner"
init: false
arch:
  - aarch64
  - amd64
  - armv7

apparmor: true
backup: hot
tmpfs: true
stage: stable

options:
  mining_pool: "pool:port"
  wallet: "walletAddress"
  password: "x"
  threads: "1"
  mode: "light"
schema:
  mining_pool: str
  wallet: str
  password: password?
  threads: int
  mode: list(auto|fast|light)
